# Generated by Claude Opus 4.5, chat ID: https://claude.ai/chat/2354d954-a604-4b26-869f-27cfded2f616
import pytest
import torch
from typing import List, Tuple

from .tuple_dataloader_tst_common import (
    N_POINTS,
    create_mined_batch_data,
    create_fa_batch_data,
    get_expected_negative_indices_in_fa,
)

# Adjust these imports to match your actual module paths
from dataloaders.patch_triplet_dataloaders import collate_ms_batches
from miners import SimpleMiner


# =============================================================================
# SimpleMiner Tests (copy_negatives=False)
# =============================================================================

class TestSimpleMiner:
    """Test suite for SimpleMiner with copy_negatives=False."""

    @pytest.fixture
    def miner(self):
        miner = SimpleMiner()
        miner.copy_negatives = False
        return miner

    def test_mined_patches_unchanged(self, miner):
        """Verify that mined_patches is not modified (copy_negatives=False)."""
        mined_tuple_sizes = [3, 2, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        original_mined_shape = mined_patches.shape
        original_mined_clone = mined_patches.clone()

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_patches = mined_result.patches

        assert result_mined_patches.shape == original_mined_shape, \
            "mined_patches shape should be unchanged when copy_negatives=False"
        assert torch.equal(result_mined_patches, original_mined_clone), \
            "mined_patches content should be unchanged"

    def test_fa_batch_unchanged(self, miner):
        """Verify that fa_patches and fa_indices are returned unchanged."""
        mined_tuple_sizes = [3, 2, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        fa_patches_clone = fa_patches.clone()
        fa_indices_clone = tuple(t.clone() for t in fa_indices)

        _, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_fa_patches = fa_result.patches
        result_fa_indices = fa_result.indices_tuple

        assert torch.equal(result_fa_patches, fa_patches_clone), \
            "fa_patches should be unchanged"
        for i in range(4):
            assert torch.equal(result_fa_indices[i], fa_indices_clone[i]), \
                f"fa_indices[{i}] should be unchanged"

    def test_mined_indices_0_1_unchanged(self, miner):
        """Verify that mined_indices[0] and [1] (positive pairs) are unchanged."""
        mined_tuple_sizes = [3, 2, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        original_idx_0 = mined_indices[0].clone()
        original_idx_1 = mined_indices[1].clone()

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_indices = mined_result.indices_tuple

        assert torch.equal(result_mined_indices[0], original_idx_0), \
            "mined_indices[0] should be unchanged"
        assert torch.equal(result_mined_indices[1], original_idx_1), \
            "mined_indices[1] should be unchanged"

    def test_mined_indices_2_3_cartesian_product(self, miner):
        """Verify mined_indices[2] and [3] contain correct Cartesian product."""
        mined_tuple_sizes = [3, 2, 2]  # 7 positives total
        fa_tuple_sizes = [2, 3]  # 2 negatives total

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        num_mined_positives = sum(mined_tuple_sizes)  # 7

        # Get negative indices within FA batch
        fa_negative_indices = get_expected_negative_indices_in_fa(fa_tuple_sizes)  # [2, 6]

        # After mining, negative indices should be offset by mined batch size
        expected_negative_indices_after_offset = [num_mined_positives + idx for idx in fa_negative_indices]  # [9, 13]

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_indices = mined_result.indices_tuple

        # Expected Cartesian product: each positive paired with each negative
        # Order: (p0, n0), (p0, n1), (p1, n0), (p1, n1), ...
        expected_idx_2 = []
        expected_idx_3 = []

        for pos_idx in range(num_mined_positives):
            for neg_idx in expected_negative_indices_after_offset:
                expected_idx_2.append(pos_idx)
                expected_idx_3.append(neg_idx)

        actual_idx_2 = result_mined_indices[2].tolist()
        actual_idx_3 = result_mined_indices[3].tolist()

        assert actual_idx_2 == expected_idx_2, \
            f"mined_indices[2] mismatch.\nExpected: {expected_idx_2}\nActual: {actual_idx_2}"
        assert actual_idx_3 == expected_idx_3, \
            f"mined_indices[3] mismatch.\nExpected: {expected_idx_3}\nActual: {actual_idx_3}"

    def test_mined_indices_2_3_pair_count(self, miner):
        """Verify correct number of (positive, negative) pairs."""
        mined_tuple_sizes = [3, 2, 4]
        fa_tuple_sizes = [2, 3, 2]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        num_positives = sum(mined_tuple_sizes)
        num_negatives = len(fa_tuple_sizes)
        expected_pair_count = num_positives * num_negatives

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_indices = mined_result.indices_tuple

        assert result_mined_indices[2].shape[0] == expected_pair_count, \
            f"Expected {expected_pair_count} pairs, got {result_mined_indices[2].shape[0]}"
        assert result_mined_indices[3].shape[0] == expected_pair_count, \
            f"Expected {expected_pair_count} pairs, got {result_mined_indices[3].shape[0]}"

    @pytest.mark.parametrize("mined_sizes,fa_sizes", [
        ([2], [2]),
        ([3, 2, 2], [2, 3]),
        ([5], [2, 2, 2]),
        ([2, 2, 2], [5]),
        ([10], [10]),
        ([2, 3, 4, 5], [2, 3, 4]),
    ])
    def test_various_configurations(self, miner, mined_sizes, fa_sizes):
        """Test various mined/FA batch configurations."""
        mined_patches, mined_indices = create_mined_batch_data(mined_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_sizes)

        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_patches = mined_result.patches
        result_mined_indices = mined_result.indices_tuple
        result_fa_patches = fa_result.patches
        result_fa_indices = fa_result.indices_tuple

        assert len(result_mined_indices) == 4
        assert len(result_fa_indices) == 4

        num_positives = sum(mined_sizes)
        num_negatives = len(fa_sizes)
        expected_pairs = num_positives * num_negatives

        assert result_mined_indices[2].shape[0] == expected_pairs
        assert result_mined_indices[3].shape[0] == expected_pairs

    def test_output_tensor_types(self, miner):
        """Verify output tensor dtypes."""
        mined_patches, mined_indices = create_mined_batch_data([3, 2])
        fa_patches, fa_indices = create_fa_batch_data([2, 3])

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_indices = mined_result.indices_tuple

        assert result_mined_indices[2].dtype == torch.long
        assert result_mined_indices[3].dtype == torch.long


# =============================================================================
# collate_ms_batches Tests
# =============================================================================

class TestCollateMsBatches:
    """Test suite for collate_ms_batches function."""

    def test_patches_concatenated_correctly(self):
        """Verify patches are concatenated: [mined, fa]."""
        mined_tuple_sizes = [3, 2, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        total_mined = mined_patches.shape[0]
        total_fa = fa_patches.shape[0]

        patches, _, _ = collate_ms_batches(mined_patches, mined_indices, fa_patches, fa_indices)

        assert patches.shape[0] == total_mined + total_fa, \
            f"Expected {total_mined + total_fa} patches, got {patches.shape[0]}"

        assert torch.equal(patches[:total_mined], mined_patches), \
            "First part should be mined_patches"

        # Note: fa_patches is modified in-place by collate, so compare with original values
        # The fa_patches tensor content is unchanged, only fa_indices are offset

    def test_patches_order_preserved(self):
        """Verify patch order is preserved using signatures."""
        mined_tuple_sizes = [3, 2]  # 5 patches, signatures 0-4
        fa_tuple_sizes = [2, 2]  # 6 patches (4 pos + 2 neg)

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes, signature_offset=1000)

        patches, _, _ = collate_ms_batches(mined_patches, mined_indices, fa_patches, fa_indices)

        # Check mined signatures (0, 1, 2, 3, 4)
        for i in range(5):
            sig = patches[i, 0, 0].item()
            assert sig == float(i), f"Mined patch {i} has wrong signature: {sig}"

        # Check FA patches start at index 5
        assert patches[5, 0, 0].item() == 1000.0, "First FA patch should have signature 1000"

    def test_mined_indices_unchanged(self):
        """Verify mined_indices is not modified by collate."""
        mined_tuple_sizes = [3, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        mined_indices_clone = tuple(t.clone() for t in mined_indices)

        _, result_mined_indices, _ = collate_ms_batches(
            mined_patches, mined_indices, fa_patches, fa_indices
        )

        for i in range(4):
            assert torch.equal(result_mined_indices[i], mined_indices_clone[i]), \
                f"mined_indices[{i}] should be unchanged"

    def test_fa_indices_offset_applied(self):
        """Verify FA indices are offset by mined batch size."""
        mined_tuple_sizes = [3, 2, 2]  # 7 patches
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        offset = mined_patches.shape[0]  # 7
        fa_indices_before = tuple(t.clone() for t in fa_indices)

        _, _, result_fa_indices = collate_ms_batches(
            mined_patches, mined_indices, fa_patches, fa_indices
        )

        for i in range(4):
            expected = fa_indices_before[i] + offset
            assert torch.equal(result_fa_indices[i], expected), \
                f"fa_indices[{i}] should be offset by {offset}"

    def test_fa_indices_offset_values(self):
        """Verify specific FA index values after offset."""
        mined_tuple_sizes = [3, 2, 2]  # 7 mined patches
        fa_tuple_sizes = [2, 3]  # FA: [p0, p1, n0, p2, p3, p4, n1]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        offset = 7  # mined batch size

        _, _, result_fa_indices = collate_ms_batches(
            mined_patches, mined_indices, fa_patches, fa_indices
        )

        # After collate, negatives should be at 7+2=9 and 7+6=13
        unique_neg_indices = torch.unique(result_fa_indices[3]).tolist()
        expected_after_offset = [9, 13]

        assert sorted(unique_neg_indices) == expected_after_offset, \
            f"FA negative indices after offset should be {expected_after_offset}, got {unique_neg_indices}"

    @pytest.mark.parametrize("mined_sizes,fa_sizes", [
        ([2], [2]),
        ([3, 2, 2], [2, 3]),
        ([5], [2, 2, 2]),
        ([2, 2, 2], [5]),
        ([10], [10]),
    ])
    def test_various_configurations(self, mined_sizes, fa_sizes):
        """Test collation with various batch configurations."""
        mined_patches, mined_indices = create_mined_batch_data(mined_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_sizes)

        total_mined = sum(mined_sizes)
        total_fa = sum(s + 1 for s in fa_sizes)

        patches, result_mined_indices, result_fa_indices = collate_ms_batches(
            mined_patches, mined_indices, fa_patches, fa_indices
        )

        assert patches.shape[0] == total_mined + total_fa
        assert len(result_mined_indices) == 4
        assert len(result_fa_indices) == 4


# =============================================================================
# Integration Tests: SimpleMiner + collate_ms_batches
# =============================================================================

class TestMinerAndCollateIntegration:
    """Integration tests for SimpleMiner followed by collate_ms_batches."""

    @pytest.fixture
    def miner(self):
        miner = SimpleMiner()
        miner.copy_negatives = False
        return miner

    def test_full_pipeline_your_example(self, miner):
        """Test the full pipeline with your example configuration."""
        mined_tuple_sizes = [3, 2, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        # Step 1: Mine
        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        mined_patches_out = mined_result.patches
        mined_indices_out = mined_result.indices_tuple
        fa_patches_out = fa_result.patches
        fa_indices_out = fa_result.indices_tuple

        # Step 2: Collate
        patches, mined_indices_final, fa_indices_final = collate_ms_batches(
            mined_patches_out, mined_indices_out, fa_patches_out, fa_indices_out
        )

        # Verify total patches
        assert patches.shape[0] == 14, f"Expected 14 patches, got {patches.shape[0]}"

        # Verify mined_indices[2] contains all positive indices 0-6
        unique_anchors = torch.unique(mined_indices_final[2]).tolist()
        assert unique_anchors == list(range(7)), \
            f"Expected anchors [0..6], got {unique_anchors}"

        # Verify mined_indices[3] contains offset negative indices
        unique_negatives = sorted(torch.unique(mined_indices_final[3]).tolist())
        assert unique_negatives == [9, 13], \
            f"Expected negative indices [9, 13], got {unique_negatives}"

        # Verify pair count: 7 positives × 2 negatives = 14 pairs
        assert mined_indices_final[2].shape[0] == 14
        assert mined_indices_final[3].shape[0] == 14

    def test_negative_indices_point_to_actual_negatives(self, miner):
        """Verify that negative indices in mined_indices[3] point to negative patches."""
        mined_tuple_sizes = [3, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes, neg_signature_start=-100.0)

        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        mined_patches_out = mined_result.patches
        mined_indices_out = mined_result.indices_tuple
        fa_patches_out = fa_result.patches
        fa_indices_out = fa_result.indices_tuple

        patches, mined_indices_final, _ = collate_ms_batches(
            mined_patches_out, mined_indices_out, fa_patches_out, fa_indices_out
        )

        negative_indices = torch.unique(mined_indices_final[3])
        for neg_idx in negative_indices.tolist():
            signature = patches[neg_idx, 0, 0].item()
            assert signature < 0, \
                f"Index {neg_idx} points to patch with signature {signature}, expected negative"

    def test_positive_indices_point_to_mined_positives(self, miner):
        """Verify that anchor indices in mined_indices[2] point to mined positive patches."""
        mined_tuple_sizes = [3, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes, signature_offset=1000)

        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        mined_patches_out = mined_result.patches
        mined_indices_out = mined_result.indices_tuple
        fa_patches_out = fa_result.patches
        fa_indices_out = fa_result.indices_tuple

        patches, mined_indices_final, _ = collate_ms_batches(
            mined_patches_out, mined_indices_out, fa_patches_out, fa_indices_out
        )

        anchor_indices = torch.unique(mined_indices_final[2])
        num_mined = sum(mined_tuple_sizes)

        for anchor_idx in anchor_indices.tolist():
            assert anchor_idx < num_mined, \
                f"Anchor index {anchor_idx} should be < {num_mined}"
            signature = patches[anchor_idx, 0, 0].item()
            assert 0 <= signature < num_mined, \
                f"Anchor at {anchor_idx} has signature {signature}, expected in [0, {num_mined})"

    @pytest.mark.parametrize("mined_sizes,fa_sizes", [
        ([2], [2]),
        ([3, 2, 2], [2, 3]),
        ([5, 5], [3, 3, 3]),
        ([2, 3, 4, 5], [2, 3]),
    ])
    def test_full_pipeline_various_configs(self, miner, mined_sizes, fa_sizes):
        """Test full pipeline with various configurations."""
        mined_patches, mined_indices = create_mined_batch_data(mined_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_sizes)

        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        mined_patches_out = mined_result.patches
        mined_indices_out = mined_result.indices_tuple
        fa_patches_out = fa_result.patches
        fa_indices_out = fa_result.indices_tuple

        patches, mined_indices_final, fa_indices_final = collate_ms_batches(
            mined_patches_out, mined_indices_out, fa_patches_out, fa_indices_out
        )

        num_mined = sum(mined_sizes)
        num_fa = sum(s + 1 for s in fa_sizes)
        num_negatives = len(fa_sizes)

        assert patches.shape[0] == num_mined + num_fa

        expected_pairs = num_mined * num_negatives
        assert mined_indices_final[2].shape[0] == expected_pairs
        assert mined_indices_final[3].shape[0] == expected_pairs


# =============================================================================
# SimpleMiner Tests (copy_negatives=True)
# =============================================================================

class TestSimpleMinerCopyNegatives:
    """Test suite for SimpleMiner with copy_negatives=True."""

    @pytest.fixture
    def miner(self):
        miner = SimpleMiner()
        miner.copy_negatives = True
        return miner

    def test_mined_patches_extended_with_negatives(self, miner):
        """Verify that mined_patches is extended with negative patches."""
        mined_tuple_sizes = [3, 2, 2]  # 7 positives
        fa_tuple_sizes = [2, 3]  # 2 negatives

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes, neg_signature_start=-100.0)

        original_mined_count = mined_patches.shape[0]  # 7
        num_negatives = len(fa_tuple_sizes)  # 2

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_patches = mined_result.patches

        expected_count = original_mined_count + num_negatives  # 9
        assert result_mined_patches.shape[0] == expected_count, \
            f"Expected {expected_count} patches, got {result_mined_patches.shape[0]}"

    def test_appended_patches_are_negatives(self, miner):
        """Verify that appended patches have negative signatures."""
        mined_tuple_sizes = [3, 2, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes, neg_signature_start=-100.0)

        original_mined_count = mined_patches.shape[0]

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_patches = mined_result.patches

        # Check appended patches (indices 7 and 8) have negative signatures
        for i in range(original_mined_count, result_mined_patches.shape[0]):
            signature = result_mined_patches[i, 0, 0].item()
            assert signature < 0, \
                f"Appended patch at index {i} has signature {signature}, expected negative"

    def test_mined_indices_2_3_point_to_appended_negatives(self, miner):
        """Verify mined_indices[3] points to appended negative indices."""
        mined_tuple_sizes = [3, 2, 2]  # 7 positives
        fa_tuple_sizes = [2, 3]  # 2 negatives

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        num_mined_positives = sum(mined_tuple_sizes)  # 7
        num_negatives = len(fa_tuple_sizes)  # 2

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_indices = mined_result.indices_tuple

        # Negatives should be at indices 7 and 8 (appended to mined_patches)
        expected_negative_indices = list(range(num_mined_positives, num_mined_positives + num_negatives))
        unique_negatives = sorted(torch.unique(result_mined_indices[3]).tolist())

        assert unique_negatives == expected_negative_indices, \
            f"Expected negative indices {expected_negative_indices}, got {unique_negatives}"

    def test_mined_indices_2_3_cartesian_product(self, miner):
        """Verify correct Cartesian product for copy_negatives=True."""
        mined_tuple_sizes = [3, 2, 2]  # 7 positives
        fa_tuple_sizes = [2, 3]  # 2 negatives

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        num_positives = sum(mined_tuple_sizes)  # 7
        num_negatives = len(fa_tuple_sizes)  # 2

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_indices = mined_result.indices_tuple

        # Expected: each positive (0-6) paired with each negative (7, 8)
        expected_idx_2 = []
        expected_idx_3 = []
        for pos_idx in range(num_positives):
            for neg_idx in range(num_positives, num_positives + num_negatives):
                expected_idx_2.append(pos_idx)
                expected_idx_3.append(neg_idx)

        assert result_mined_indices[2].tolist() == expected_idx_2, \
            f"mined_indices[2] mismatch"
        assert result_mined_indices[3].tolist() == expected_idx_3, \
            f"mined_indices[3] mismatch"

    def test_mined_indices_0_1_unchanged(self, miner):
        """Verify positive pair indices are unchanged."""
        mined_tuple_sizes = [3, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes)

        original_idx_0 = mined_indices[0].clone()
        original_idx_1 = mined_indices[1].clone()

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_indices = mined_result.indices_tuple

        assert torch.equal(result_mined_indices[0], original_idx_0)
        assert torch.equal(result_mined_indices[1], original_idx_1)

    @pytest.mark.parametrize("mined_sizes,fa_sizes", [
        ([2], [2]),
        ([3, 2, 2], [2, 3]),
        ([5], [2, 2, 2]),
        ([2, 3, 4], [3, 3]),
    ])
    def test_various_configurations(self, miner, mined_sizes, fa_sizes):
        """Test various configurations with copy_negatives=True."""
        mined_patches, mined_indices = create_mined_batch_data(mined_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_sizes)

        num_positives = sum(mined_sizes)
        num_negatives = len(fa_sizes)

        mined_result, _ = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        result_mined_patches = mined_result.patches
        result_mined_indices = mined_result.indices_tuple

        # Verify extended patch count
        assert result_mined_patches.shape[0] == num_positives + num_negatives

        # Verify pair count
        expected_pairs = num_positives * num_negatives
        assert result_mined_indices[2].shape[0] == expected_pairs
        assert result_mined_indices[3].shape[0] == expected_pairs


# =============================================================================
# Integration Tests: SimpleMiner (copy_negatives=True) + collate_ms_batches
# =============================================================================

class TestMinerCopyNegativesAndCollateIntegration:
    """Integration tests for SimpleMiner (copy_negatives=True) + collate_ms_batches."""

    @pytest.fixture
    def miner(self):
        miner = SimpleMiner()
        miner.copy_negatives = True
        return miner

    def test_full_pipeline_your_example(self, miner):
        """Test full pipeline with copy_negatives=True.

        mined_patches = [p11,p12,p13,p21,p22,p31,p32] (7)
        fa_patches = [p11', p12', n1, p21', p22', p23', n2] (7)

        After mine: mined_patches = [p0..p6, n0, n1] (9)
        After collate: patches = [p0..p6, n0, n1, fa0..fa6] (16)

        mined_indices[3] should point to indices 7, 8 (the copied negatives)
        fa_indices should be offset by 9 (extended mined batch size)
        """
        mined_tuple_sizes = [3, 2, 2]  # 7 positives
        fa_tuple_sizes = [2, 3]  # 2 negatives, 7 total patches

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes, neg_signature_start=-100.0)

        # Step 1: Mine
        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        mined_patches_out = mined_result.patches
        mined_indices_out = mined_result.indices_tuple
        fa_patches_out = fa_result.patches
        fa_indices_out = fa_result.indices_tuple

        # Verify mined_patches extended: 7 + 2 = 9
        assert mined_patches_out.shape[0] == 9

        # Step 2: Collate
        patches, mined_indices_final, fa_indices_final = collate_ms_batches(
            mined_patches_out, mined_indices_out, fa_patches_out, fa_indices_out
        )

        # Total patches: 9 (extended mined) + 7 (fa) = 16
        assert patches.shape[0] == 16

        # mined_indices[3] should point to 7, 8 (copied negatives within mined)
        unique_mined_negatives = sorted(torch.unique(mined_indices_final[3]).tolist())
        assert unique_mined_negatives == [7, 8], \
            f"Expected mined negative indices [7, 8], got {unique_mined_negatives}"

        # fa_indices should be offset by 9 (extended mined batch size)
        # Original FA negatives were at indices 2 and 6
        # After offset: 9+2=11 and 9+6=15
        unique_fa_negatives = sorted(torch.unique(fa_indices_final[3]).tolist())
        assert unique_fa_negatives == [11, 15], \
            f"Expected FA negative indices [11, 15], got {unique_fa_negatives}"

    def test_negative_indices_point_to_actual_negatives(self, miner):
        """Verify all negative indices point to patches with negative signatures."""
        mined_tuple_sizes = [3, 2]
        fa_tuple_sizes = [2, 3]

        mined_patches, mined_indices = create_mined_batch_data(mined_tuple_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_tuple_sizes, neg_signature_start=-100.0)

        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        mined_patches_out = mined_result.patches
        mined_indices_out = mined_result.indices_tuple
        fa_patches_out = fa_result.patches
        fa_indices_out = fa_result.indices_tuple

        patches, mined_indices_final, fa_indices_final = collate_ms_batches(
            mined_patches_out, mined_indices_out, fa_patches_out, fa_indices_out
        )

        # Check mined negative indices
        for neg_idx in torch.unique(mined_indices_final[3]).tolist():
            signature = patches[neg_idx, 0, 0].item()
            assert signature < 0, \
                f"Mined negative index {neg_idx} points to signature {signature}"

        # Check FA negative indices
        for neg_idx in torch.unique(fa_indices_final[3]).tolist():
            signature = patches[neg_idx, 0, 0].item()
            assert signature < 0, \
                f"FA negative index {neg_idx} points to signature {signature}"

    @pytest.mark.parametrize("mined_sizes,fa_sizes", [
        ([2], [2]),
        ([3, 2, 2], [2, 3]),
        ([5, 5], [3, 3, 3]),
    ])
    def test_full_pipeline_various_configs(self, miner, mined_sizes, fa_sizes):
        """Test full pipeline with various configurations."""
        mined_patches, mined_indices = create_mined_batch_data(mined_sizes)
        fa_patches, fa_indices = create_fa_batch_data(fa_sizes)

        num_mined_positives = sum(mined_sizes)
        num_fa_patches = sum(s + 1 for s in fa_sizes)
        num_negatives = len(fa_sizes)

        mined_result, fa_result = miner.mine(
            mined_patches, mined_indices, fa_patches, fa_indices
        )
        mined_patches_out = mined_result.patches
        mined_indices_out = mined_result.indices_tuple
        fa_patches_out = fa_result.patches
        fa_indices_out = fa_result.indices_tuple

        patches, mined_indices_final, fa_indices_final = collate_ms_batches(
            mined_patches_out, mined_indices_out, fa_patches_out, fa_indices_out
        )

        # Total patches: (mined + copied negatives) + fa
        expected_total = (num_mined_positives + num_negatives) + num_fa_patches
        assert patches.shape[0] == expected_total

        # Verify pair counts
        expected_mined_pairs = num_mined_positives * num_negatives
        assert mined_indices_final[2].shape[0] == expected_mined_pairs
        assert mined_indices_final[3].shape[0] == expected_mined_pairs




# =============================================================================
# Standalone test runner
# =============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])


