# Generated by Claude Opus 4.5, chat ID: https://claude.ai/chat/2354d954-a604-4b26-869f-27cfded2f616
import pytest
import torch
from typing import List, Tuple

from .tuple_dataloader_tst_common import (
    N_POINTS,
    create_batch,
    create_batch_with_negatives,
    create_tuple_with_negative,
    compute_expected_indices,
    compute_expected_indices_with_negatives,
    compute_expected_valid_indices,
    compute_expected_valid_indices_with_negatives,
)

# Adjust this import to match your actual module path
from dataloaders.patch_triplet_dataloaders import AllPositiveTupleCollator, SingleNegativeTupleCollator


# =============================================================================
# AllPositiveTupleCollator Tests
# =============================================================================

class TestAllPositiveTupleCollator:
    """Test suite for AllPositiveTupleCollator."""

    @pytest.fixture
    def collator(self):
        return AllPositiveTupleCollator()

    def verify_patches_order(self, output_patches: torch.Tensor, tuple_sizes: List[int]):
        """Verify that patches are flattened in the correct order."""
        total_patches = sum(tuple_sizes)
        assert output_patches.shape == (total_patches, N_POINTS, 3), \
            f"Expected shape {(total_patches, N_POINTS, 3)}, got {output_patches.shape}"

        for i in range(total_patches):
            expected_signature = float(i)
            actual_value = output_patches[i, 0, 0].item()
            assert actual_value == expected_signature, \
                f"Patch at index {i} has signature {actual_value}, expected {expected_signature}"

    def verify_valid_indices(
            self,
            actual_indices: Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor],
            tuple_sizes: List[int]
    ):
        """Verify that valid_indices contains correct Cartesian product pairs."""
        index_ranges = compute_expected_indices(tuple_sizes)
        expected = compute_expected_valid_indices(index_ranges)

        assert len(actual_indices) == 4, f"Expected 4-tuple, got {len(actual_indices)}"

        actual_anchors = actual_indices[0].tolist()
        actual_positives = actual_indices[1].tolist()
        actual_empty1 = actual_indices[2].tolist()
        actual_empty2 = actual_indices[3].tolist()

        assert actual_empty1 == [], f"Expected empty list for index 2, got {actual_empty1}"
        assert actual_empty2 == [], f"Expected empty list for index 3, got {actual_empty2}"

        assert actual_anchors == expected[0], \
            f"Anchors mismatch.\nExpected: {expected[0]}\nActual: {actual_anchors}"
        assert actual_positives == expected[1], \
            f"Positives mismatch.\nExpected: {expected[1]}\nActual: {actual_positives}"

    @pytest.mark.parametrize("tuple_sizes", [
        [2],
        [3],
        [5],
    ])
    def test_single_tuple(self, collator, tuple_sizes):
        """Test with a single tuple of varying sizes."""
        batch = create_batch(tuple_sizes)
        result = collator(batch)

        self.verify_patches_order(result['patches'], tuple_sizes)
        self.verify_valid_indices(result['valid_indices'], tuple_sizes)

    @pytest.mark.parametrize("tuple_sizes", [
        [2, 2],
        [3, 2],
        [2, 3],
        [3, 2, 2],
        [2, 3, 4],
        [4, 3, 2],
    ])
    def test_multiple_tuples(self, collator, tuple_sizes):
        """Test with multiple tuples of varying sizes."""
        batch = create_batch(tuple_sizes)
        result = collator(batch)

        self.verify_patches_order(result['patches'], tuple_sizes)
        self.verify_valid_indices(result['valid_indices'], tuple_sizes)

    @pytest.mark.parametrize("tuple_sizes", [
        [2, 2, 2, 2, 2],
        [10],
        [5, 5, 5],
    ])
    def test_various_batch_configurations(self, collator, tuple_sizes):
        """Test various batch configurations."""
        batch = create_batch(tuple_sizes)
        result = collator(batch)

        self.verify_patches_order(result['patches'], tuple_sizes)
        self.verify_valid_indices(result['valid_indices'], tuple_sizes)

    def test_with_none_entries(self, collator):
        """Test that None entries in batch are skipped correctly."""
        tuple_sizes = [3, 2]
        batch = create_batch(tuple_sizes)
        batch_with_nones = [None, batch[0], None, batch[1], None]

        result = collator(batch_with_nones)

        self.verify_patches_order(result['patches'], tuple_sizes)
        self.verify_valid_indices(result['valid_indices'], tuple_sizes)

    def test_all_none_raises_error(self, collator):
        """Test that a batch of all None entries raises RuntimeError."""
        batch = [None, None, None]

        with pytest.raises(RuntimeError, match="empty batch"):
            collator(batch)

    def test_output_tensor_types(self, collator):
        """Verify output tensor dtypes."""
        batch = create_batch([3, 2])
        result = collator(batch)

        assert result['patches'].dtype == torch.float32
        assert result['valid_indices'][0].dtype == torch.long
        assert result['valid_indices'][1].dtype == torch.long
        assert result['valid_indices'][2].dtype == torch.long
        assert result['valid_indices'][3].dtype == torch.long

    def test_valid_indices_pair_count(self, collator):
        """Verify the correct number of pairs is generated."""
        tuple_sizes = [3, 2, 4]
        expected_pair_count = sum(m * (m - 1) for m in tuple_sizes)

        batch = create_batch(tuple_sizes)
        result = collator(batch)

        actual_pair_count = result['valid_indices'][0].shape[0]
        assert actual_pair_count == expected_pair_count, \
            f"Expected {expected_pair_count} pairs, got {actual_pair_count}"


# =============================================================================
# SingleNegativeTupleCollator Tests
# =============================================================================

class TestSingleNegativeTupleCollator:
    """Test suite for SingleNegativeTupleCollator."""

    @pytest.fixture
    def collator(self):
        return SingleNegativeTupleCollator()

    def verify_patches_order_with_negatives(
            self,
            output_patches: torch.Tensor,
            tuple_sizes: List[int]
    ):
        """Verify patches are flattened correctly: positives followed by negative for each tuple."""
        total_patches = sum(size + 1 for size in tuple_sizes)
        assert output_patches.shape == (total_patches, N_POINTS, 3), \
            f"Expected shape {(total_patches, N_POINTS, 3)}, got {output_patches.shape}"

        current_idx = 0
        expected_positive_signature = 0
        negative_signature = -1.0

        for size in tuple_sizes:
            # Check positive patches
            for i in range(size):
                actual_value = output_patches[current_idx, 0, 0].item()
                assert actual_value == float(expected_positive_signature), \
                    f"Patch at index {current_idx} has signature {actual_value}, " \
                    f"expected {expected_positive_signature} (positive)"
                current_idx += 1
                expected_positive_signature += 1

            # Check negative patch
            actual_value = output_patches[current_idx, 0, 0].item()
            assert actual_value == negative_signature, \
                f"Patch at index {current_idx} has signature {actual_value}, " \
                f"expected {negative_signature} (negative)"
            current_idx += 1
            expected_positive_signature += 1
            negative_signature -= 1.0

    def verify_valid_indices_with_negatives(
            self,
            actual_indices: Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor],
            tuple_sizes: List[int]
    ):
        """Verify valid_indices for tuples with negatives."""
        positive_ranges, negative_idxs = compute_expected_indices_with_negatives(tuple_sizes)
        expected = compute_expected_valid_indices_with_negatives(positive_ranges, negative_idxs)

        assert len(actual_indices) == 4, f"Expected 4-tuple, got {len(actual_indices)}"

        actual_idx_ap = actual_indices[0].tolist()
        actual_idx_p = actual_indices[1].tolist()
        actual_idx_an = actual_indices[2].tolist()
        actual_idx_n = actual_indices[3].tolist()

        assert actual_idx_ap == expected[0], \
            f"idx_ap mismatch.\nExpected: {expected[0]}\nActual: {actual_idx_ap}"
        assert actual_idx_p == expected[1], \
            f"idx_p mismatch.\nExpected: {expected[1]}\nActual: {actual_idx_p}"
        assert actual_idx_an == expected[2], \
            f"idx_an mismatch.\nExpected: {expected[2]}\nActual: {actual_idx_an}"
        assert actual_idx_n == expected[3], \
            f"idx_n mismatch.\nExpected: {expected[3]}\nActual: {actual_idx_n}"

    @pytest.mark.parametrize("tuple_sizes", [
        [2],
        [3],
        [5],
    ])
    def test_single_tuple(self, collator, tuple_sizes):
        """Test with a single tuple containing positives and one negative."""
        batch = create_batch_with_negatives(tuple_sizes)
        result = collator(batch)

        self.verify_patches_order_with_negatives(result['patches'], tuple_sizes)
        self.verify_valid_indices_with_negatives(result['valid_indices'], tuple_sizes)

    @pytest.mark.parametrize("tuple_sizes", [
        [2, 2],
        [3, 2],
        [2, 3],
        [3, 2, 2],
        [2, 3, 4],
        [4, 3, 2],
    ])
    def test_multiple_tuples(self, collator, tuple_sizes):
        """Test with multiple tuples, each with positives and one negative."""
        batch = create_batch_with_negatives(tuple_sizes)
        result = collator(batch)

        self.verify_patches_order_with_negatives(result['patches'], tuple_sizes)
        self.verify_valid_indices_with_negatives(result['valid_indices'], tuple_sizes)

    @pytest.mark.parametrize("tuple_sizes", [
        [2, 2, 2, 2, 2],
        [10],
        [5, 5, 5],
    ])
    def test_various_batch_configurations(self, collator, tuple_sizes):
        """Test various batch configurations."""
        batch = create_batch_with_negatives(tuple_sizes)
        result = collator(batch)

        self.verify_patches_order_with_negatives(result['patches'], tuple_sizes)
        self.verify_valid_indices_with_negatives(result['valid_indices'], tuple_sizes)

    def test_with_none_entries(self, collator):
        """Test that None entries in batch are skipped correctly."""
        tuple_sizes = [3, 2]
        batch = create_batch_with_negatives(tuple_sizes)
        batch_with_nones = [None, batch[0], None, batch[1], None]

        result = collator(batch_with_nones)

        self.verify_patches_order_with_negatives(result['patches'], tuple_sizes)
        self.verify_valid_indices_with_negatives(result['valid_indices'], tuple_sizes)

    def test_single_positive_skipped(self, collator):
        """Test that tuples with only 1 positive (+ 1 negative) are skipped."""
        valid_tuple = create_tuple_with_negative(num_positive=3, start_signature=0, negative_signature=-1.0)
        single_positive_tuple = create_tuple_with_negative(num_positive=1, start_signature=100,
                                                           negative_signature=-100.0)

        batch = [valid_tuple, single_positive_tuple]
        result = collator(batch)

        assert result['patches'].shape[0] == 4, \
            f"Expected 4 patches (single-positive tuple should be skipped), got {result['patches'].shape[0]}"

        all_signatures = result['patches'][:, 0, 0].tolist()
        assert 100.0 not in all_signatures, "Single-positive tuple's positive patch should not appear"
        assert -100.0 not in all_signatures, "Single-positive tuple's negative patch should not appear"

    def test_all_single_positive_raises_error(self, collator):
        """Test that a batch of all single-positive tuples raises RuntimeError."""
        single_pos_1 = create_tuple_with_negative(num_positive=1, start_signature=0, negative_signature=-1.0)
        single_pos_2 = create_tuple_with_negative(num_positive=1, start_signature=10, negative_signature=-2.0)

        batch = [single_pos_1, single_pos_2]

        with pytest.raises(RuntimeError, match="empty batch"):
            collator(batch)

    def test_all_none_raises_error(self, collator):
        """Test that a batch of all None entries raises RuntimeError."""
        batch = [None, None, None]

        with pytest.raises(RuntimeError, match="empty batch"):
            collator(batch)

    def test_mixed_none_and_single_positive_raises_error(self, collator):
        """Test that a batch with only None and single-positive tuples raises RuntimeError."""
        single_pos = create_tuple_with_negative(num_positive=1, start_signature=0, negative_signature=-1.0)
        batch = [None, single_pos, None]

        with pytest.raises(RuntimeError, match="empty batch"):
            collator(batch)

    def test_output_tensor_types(self, collator):
        """Verify output tensor dtypes."""
        batch = create_batch_with_negatives([3, 2])
        result = collator(batch)

        assert result['patches'].dtype == torch.float32
        assert result['valid_indices'][0].dtype == torch.long
        assert result['valid_indices'][1].dtype == torch.long
        assert result['valid_indices'][2].dtype == torch.long
        assert result['valid_indices'][3].dtype == torch.long

    def test_valid_indices_pair_count(self, collator):
        """Verify the correct number of pairs is generated."""
        tuple_sizes = [3, 2, 4]
        expected_pair_count = sum(m * (m - 1) for m in tuple_sizes)

        batch = create_batch_with_negatives(tuple_sizes)
        result = collator(batch)

        actual_positive_pairs = result['valid_indices'][0].shape[0]
        assert actual_positive_pairs == expected_pair_count, \
            f"Expected {expected_pair_count} positive pairs, got {actual_positive_pairs}"

        actual_negative_pairs = result['valid_indices'][2].shape[0]
        assert actual_negative_pairs == expected_pair_count, \
            f"Expected {expected_pair_count} negative pairs, got {actual_negative_pairs}"

    def test_anchor_indices_match(self, collator):
        """Verify that idx_ap and idx_an are identical."""
        batch = create_batch_with_negatives([3, 2, 2])
        result = collator(batch)

        idx_ap = result['valid_indices'][0]
        idx_an = result['valid_indices'][2]

        assert torch.equal(idx_ap, idx_an), \
            f"idx_ap and idx_an should be identical.\nidx_ap: {idx_ap.tolist()}\nidx_an: {idx_an.tolist()}"

    def test_negative_indices_point_to_negatives(self, collator):
        """Verify that all indices in idx_n point to actual negative patches."""
        tuple_sizes = [3, 2]
        batch = create_batch_with_negatives(tuple_sizes)
        result = collator(batch)

        idx_n = result['valid_indices'][3]
        patches = result['patches']

        for neg_idx in idx_n.tolist():
            signature = patches[neg_idx, 0, 0].item()
            assert signature < 0, \
                f"Index {neg_idx} in idx_n points to patch with signature {signature}, expected negative"


# =============================================================================
# Standalone test runner
# =============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v"])