# Generated by Claude Opus 4.5, chat ID: https://claude.ai/chat/2354d954-a604-4b26-869f-27cfded2f616
import pytest
import torch
from typing import List, Tuple

# Adjust these imports to match your actual module paths
from dataloaders.patch_triplet_dataloaders import AllPositiveTupleCollator, SingleNegativeTupleCollator

N_POINTS = 512


# =============================================================================
# Patch and Tuple Creation
# =============================================================================

def create_patch_with_signature(signature: float) -> torch.Tensor:
    """Create a patch tensor [N_POINTS, 3] filled with a unique signature value."""
    return torch.full((N_POINTS, 3), signature, dtype=torch.float32)


def create_tuple(num_patches: int, start_signature: int) -> dict:
    """Create a single tuple dict with num_patches patches (all positive).

    Args:
        num_patches: number of patches in this tuple (M_i)
        start_signature: the signature value for the first patch in this tuple

    Returns:
        A tuple dict with 'patches', 'num_positive_patches', 'num_negative_patches'
    """
    patches = torch.stack([
        create_patch_with_signature(float(start_signature + i))
        for i in range(num_patches)
    ], dim=0)  # Shape: [num_patches, N_POINTS, 3]

    return {
        "patches": patches,
        "num_positive_patches": num_patches,
        "num_negative_patches": 0
    }


def create_tuple_with_negative(num_positive: int, start_signature: int, negative_signature: float) -> dict:
    """Create a single tuple dict with positive patches and one negative patch.

    Args:
        num_positive: number of positive patches in this tuple (M_i)
        start_signature: the signature value for the first positive patch
        negative_signature: the signature value for the negative patch (use negative values)

    Returns:
        A tuple dict with 'patches', 'num_positive_patches', 'num_negative_patches'
    """
    positive_patches = [
        create_patch_with_signature(float(start_signature + i))
        for i in range(num_positive)
    ]
    negative_patch = create_patch_with_signature(negative_signature)

    all_patches = torch.stack(positive_patches + [negative_patch], dim=0)

    return {
        "patches": all_patches,
        "num_positive_patches": num_positive,
        "num_negative_patches": 1
    }


# =============================================================================
# Batch Creation
# =============================================================================

def create_batch(tuple_sizes: List[int]) -> List[dict]:
    """Create a batch of all-positive tuples with specified sizes.

    Args:
        tuple_sizes: list of M_i values, e.g., [3, 2, 2]

    Returns:
        List of tuple dicts forming a batch
    """
    batch = []
    start_signature = 0
    for size in tuple_sizes:
        batch.append(create_tuple(size, start_signature))
        start_signature += size
    return batch


def create_batch_with_negatives(
        tuple_sizes: List[int],
        signature_offset: int = 0,
        neg_signature_start: float = -1.0
) -> List[dict]:
    """Create a batch of tuples with positives and one negative each.

    Args:
        tuple_sizes: list of M_i values (positive counts), e.g., [3, 2, 2]
        signature_offset: starting signature for positive patches (to distinguish from other batches)
        neg_signature_start: starting signature for negative patches

    Returns:
        List of tuple dicts, each with M_i positives and 1 negative
    """
    batch = []
    start_signature = signature_offset
    negative_signature = neg_signature_start

    for size in tuple_sizes:
        batch.append(create_tuple_with_negative(size, start_signature, negative_signature))
        start_signature += size + 1  # +1 for the negative patch
        negative_signature -= 1.0

    return batch


# =============================================================================
# Index Computation Helpers
# =============================================================================

def compute_expected_indices(tuple_sizes: List[int]) -> List[List[int]]:
    """Compute the expected flat index ranges for each tuple (all-positive case).

    Args:
        tuple_sizes: list of M_i values, e.g., [3, 2, 2]

    Returns:
        List of index lists, e.g., [[0, 1, 2], [3, 4], [5, 6]]
    """
    indices = []
    current_idx = 0
    for size in tuple_sizes:
        indices.append(list(range(current_idx, current_idx + size)))
        current_idx += size
    return indices


def compute_expected_indices_with_negatives(
        tuple_sizes: List[int],
        start_idx: int = 0
) -> Tuple[List[List[int]], List[int]]:
    """Compute expected flat index ranges for tuples with negatives.

    Args:
        tuple_sizes: list of M_i values (positive counts), e.g., [3, 2, 2]
        start_idx: starting index (for offset calculations)

    Returns:
        Tuple of:
            - List of positive index lists, e.g., [[0, 1, 2], [4, 5], [7, 8]]
            - List of negative indices, e.g., [3, 6, 9]
    """
    positive_indices = []
    negative_indices = []
    current_idx = start_idx

    for size in tuple_sizes:
        positive_indices.append(list(range(current_idx, current_idx + size)))
        negative_indices.append(current_idx + size)  # Negative comes right after positives
        current_idx += size + 1  # +1 for the negative

    return positive_indices, negative_indices


def compute_expected_valid_indices(
        index_ranges: List[List[int]]
) -> Tuple[List[int], List[int], List[int], List[int]]:
    """Compute expected valid_indices for all-positive case.

    For each tuple's index range, compute the Cartesian product excluding self-pairs.

    Args:
        index_ranges: e.g., [[0, 1, 2], [3, 4], [5, 6]]

    Returns:
        Tuple of 4 lists: (anchors, positives, empty, empty)
    """
    anchors = []
    positives = []

    for indices in index_ranges:
        for anchor in indices:
            for positive in indices:
                if anchor != positive:
                    anchors.append(anchor)
                    positives.append(positive)

    return (anchors, positives, [], [])


def compute_expected_valid_indices_with_negatives(
        positive_index_ranges: List[List[int]],
        negative_indices: List[int]
) -> Tuple[List[int], List[int], List[int], List[int]]:
    """Compute expected valid_indices for tuples with negatives.

    For each (anchor, positive) pair, we also create an (anchor, negative) pair.

    Args:
        positive_index_ranges: e.g., [[0, 1, 2], [4, 5], [7, 8]]
        negative_indices: e.g., [3, 6, 9]

    Returns:
        Tuple of 4 lists: (idx_ap, idx_p, idx_an, idx_n)
    """
    idx_ap = []  # Anchor indices for positive pairs
    idx_p = []  # Positive indices
    idx_an = []  # Anchor indices for negative pairs (same as idx_ap)
    idx_n = []  # Negative indices

    for tuple_idx, indices in enumerate(positive_index_ranges):
        neg_idx = negative_indices[tuple_idx]

        for anchor in indices:
            for positive in indices:
                if anchor != positive:
                    idx_ap.append(anchor)
                    idx_p.append(positive)
                    idx_an.append(anchor)
                    idx_n.append(neg_idx)

    return (idx_ap, idx_p, idx_an, idx_n)


# =============================================================================
# Batch Data Generators (using collators)
# =============================================================================

def create_mined_batch_data(tuple_sizes: List[int]) -> Tuple[torch.Tensor, Tuple[torch.Tensor, ...]]:
    """Create mined batch data using AllPositiveTupleCollator.

    Args:
        tuple_sizes: list of M_i values (patch counts per tuple)

    Returns:
        Tuple of (patches, indices_tuple)
    """
    collator = AllPositiveTupleCollator()
    batch = create_batch(tuple_sizes)
    result = collator(batch)
    return result['patches'], result['valid_indices']


def create_fa_batch_data(
        tuple_sizes: List[int],
        signature_offset: int = 1000,
        neg_signature_start: float = -1.0
) -> Tuple[torch.Tensor, Tuple[torch.Tensor, ...]]:
    """Create FA batch data using SingleNegativeTupleCollator.

    Args:
        tuple_sizes: list of positive counts per tuple
        signature_offset: offset for positive signatures (to distinguish from mined)
        neg_signature_start: starting signature for negatives

    Returns:
        Tuple of (patches, indices_tuple)
    """
    collator = SingleNegativeTupleCollator()
    batch = create_batch_with_negatives(tuple_sizes, signature_offset, neg_signature_start)
    result = collator(batch)
    return result['patches'], result['valid_indices']


def get_expected_negative_indices_in_fa(fa_tuple_sizes: List[int]) -> List[int]:
    """Get the indices of negative patches within the FA batch.

    For FA tuples with sizes [2, 3], the structure is:
    [p0, p1, n0, p2, p3, p4, n1]
    Negatives are at indices 2 and 6.

    Args:
        fa_tuple_sizes: list of positive counts per FA tuple

    Returns:
        List of negative patch indices within the FA batch
    """
    negative_indices = []
    current_idx = 0
    for size in fa_tuple_sizes:
        current_idx += size  # Skip positives
        negative_indices.append(current_idx)  # Negative is here
        current_idx += 1  # Move past the negative
    return negative_indices


# =============================================================================
# Shared Fixtures
# =============================================================================

@pytest.fixture
def all_positive_collator():
    return AllPositiveTupleCollator()


@pytest.fixture
def single_negative_collator():
    return SingleNegativeTupleCollator()