from typing import Tuple, List, Any

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import logging
from collections import defaultdict

logger = logging.getLogger(__name__)

class MagnitudeDWA:
    """Dynamic Weight Average that considers both rate of change AND magnitude.
    Note: generated by Claude on 11/11; chat ID: https://claude.ai/chat/690f119d-7f91-4e1b-9de9-c410738f71b8
    """

    def __init__(self, alpha=0.5, temperature=1.0, target_ratio=3.0):
        """
        Args:
            alpha: Balance between rate-based (0) and magnitude-based (1) weighting
            temperature: Softmax temperature for weight computation
            target_ratio: Target contribution ratio for forced loss
        """
        self.alpha = alpha
        self.temperature = temperature
        self.target_ratio = target_ratio
        self.loss_history = {'mined': [], 'forced': []}
        self.weights_history = []
        self.momentum = 0.99
        self.current_weights = {'mined': 1.0, 'forced': 1.0, 'dwa_mined': 1.0, 'dwa_forced': 1.0, 'scale_weight': 1.0}
        self.scale_running_weight = 1.0

    def get_current_weights(self) -> Tuple[float, float]:
        return self.current_weights['mined'], self.current_weights['forced']

    def compute_weights(self, l_mined:float, l_forced:float, epoch:int):
        """Compute weights considering both change rate and magnitude."""

        # Store current losses
        self.loss_history['mined'].append(l_mined)
        self.loss_history['forced'].append(l_forced)

        if epoch < 2:
            # Initial epochs: use magnitude-based weighting only
            dwa_weights = torch.tensor([1.0, 1.0])
        else:
            # Compute rate of change (DWA component)
            rate_mined = (self.loss_history['mined'][-1] / (self.loss_history['mined'][-2] + 1e-8))
            rate_forced = (self.loss_history['forced'][-1] / (self.loss_history['forced'][-2] + 1e-8))
            dwa_weights = torch.softmax(
                torch.tensor([rate_mined, rate_forced]) / self.temperature,
                dim=0
            )
            # Scale for 2 tasks
            dwa_weights *= 2
        self.current_weights['dwa_mined'] = dwa_weights[0].item()
        self.current_weights['dwa_forced'] = dwa_weights[1].item()

        # Compute magnitude ratio
        magnitude_ratio = l_mined / (l_forced + 1e-8)
        scale_weight = self.target_ratio * magnitude_ratio
        # Apply EMA to the magnitude ratio
        self.scale_running_weight = self.momentum * self.scale_running_weight + (1 - self.momentum) * scale_weight
        self.current_weights['scale_weight'] = scale_weight
        self.current_weights['scale_running_weight'] = self.scale_running_weight

        self.current_weights['mined'] = dwa_weights[0].item()
        self.current_weights['forced'] = dwa_weights[1].item()
        self.current_weights['forced'] *= self.scale_running_weight


        self.current_weights['mined'] = 1.0
        self.current_weights['forced'] = 5.0

        return self.current_weights


class GradNorm(object):
    def __init__(self,
                 init_weights: torch.Tensor,
                 model: nn.Module,
                 num_losses:int,
                 alpha, time_window=5, iters_to_check_grad_conflict=None):
        """Computes gradient norm.

        Args:
            init_weights: Initial (default) weights tensor for GradNorm. Will be used until
                GradNorm does not accumulate enough statistics
            model: the model on which to compute gradient norms. Only parameters
                marked by "grandnorm" tags will be used to compute GradNorm.
            num_losses: the expected number of losses
            alpha: the alpha normnalization parameter (see a paper)
            time_window: the time window for the losses. Instead of comparing the current loss
                to loss at step 0, we will compare it within this time window
        """
        self.model = model

        # Get model device.
        self.device = next(model.parameters()).device
        # self.global_opt = global_opt
        self.time_window = time_window
        self.losses_history = []
        self.alpha = alpha
        self.num_losses = num_losses

        init_weights.requires_grad = True
        init_weights = init_weights.to(self.device)
        self.loss_weights_ = nn.Parameter(init_weights)

        self.reinit_params_()

        self.weights_optimizer_ = optim.Adam([self.loss_weights_], lr=1e-2)
        self.state = {
            # 'WA': init_weights[0].detach(),
            # 'FA': init_weights[1].detach()
            'WA': init_weights[0].item(),
            'FA': init_weights[1].item()
        }
        self.gradient_similarities = {}
        self.iters_to_check_grad_conflict = iters_to_check_grad_conflict
        self.counter = 0

    def reinit_params_(self):
        # Get model parameters and their names
        self.model_parameter_names = []
        self.model_parameters = []
        for module_name, module in self.model.named_modules():
            if getattr(module, "gradnorm", False):
                for param_name, param in module.named_parameters(recurse=False):
                    if param.requires_grad:
                        full_name = f"{module_name}.{param_name}" if module_name else param_name
                        self.model_parameter_names.append(full_name)
                        self.model_parameters.append(param)

    def update_loss_history(self, losses: torch.Tensor):
        """ Update the history of loss tensors, from which we  compute r_i
        """
        self.losses_history.append(losses.detach())
        if len(self.losses_history) > self.time_window:
            self.losses_history.pop()

    def grad_conflict_check_needed_(self):
        return self.iters_to_check_grad_conflict is not None and self.counter % self.iters_to_check_grad_conflict == 0

    def compute_weights(self, losses: List[torch.Tensor]):
        if len(self.losses_history) == 0:
            return self.state
        self.counter += 1
        # Compute losses inverse ratio and its mean
        L_ratio = self.losses_history[-1]/self.losses_history[0]
        mean_L = torch.mean(L_ratio)
        r = (L_ratio / mean_L)**self.alpha

        grad_norms_for_losses = []
        grads_for_losses = defaultdict(list)
        for i in range(len(losses)):
            weighted_loss = losses[i] * self.loss_weights_[i]
            # self.global_opt.zero_grad()
            # weighted_losses.backward(retain_graph=True)

            # For each module in a given list of modules, compute its gradient with regard to the
            # current loss component.
            # Retain the original computation graph for the model (we will need it for the backward pass)
            # Augment it with the new sub-graph, which will contain gradients w.r.t. the current weight
            gradients = torch.autograd.grad(
                weighted_loss, inputs = self.model_parameters, retain_graph=True, create_graph=True)
            # For each gradient, flatten it into a vector and then concatenate all entries together
            gradients_flatten = []
            if not self.grad_conflict_check_needed_():
                gradients_flatten = [g.reshape(-1) for g in gradients if g is not None]
            else:
                # Now, every number of steps to verification for gradient conflict
                for name, g in zip(self.model_parameter_names, gradients):
                    if g is None:
                        continue
                    g_flat = g.reshape(-1)
                    gradients_flatten.append(g_flat)
                    grads_for_losses[name].append(g_flat.detach())

            # parameters_to_vector may  be a faster alternative
            # grad_vec = nn.utils.parameters_to_vector([g for g in gradients if g is not None])
            grad_vec = torch.cat(gradients_flatten)
            # Compute the norms of gradients and append these to the norms array
            grad_norms_for_losses.append(grad_vec.norm(p=2))

        if self.grad_conflict_check_needed_():
            for name, gradient_list in grads_for_losses.items():
                # TOOD(alexta): this is fine for 2 losses; we don't have more than that
                assert len(gradient_list) == 2
                cosine_dist = torch.nn.functional.cosine_similarity(gradient_list[0], gradient_list[1], dim=0)
                self.gradient_similarities[name] = cosine_dist

        # Get all the gradient norms for losses. Form a tensor of gradient norms of a dimension
        # [N_losses, dim_combined_gradient]
        grad_norms_for_losses = torch.stack(grad_norms_for_losses)
        # The optimization target: mean gradient, weighted by each task convergence rate
        grad_norms_avg = grad_norms_for_losses.mean()
        # Detach this tensor, i.e. an optimization target. We consider average gradient as a constant (i.e. target);
        # we don't want to propagate grads into it.
        grad_target = (grad_norms_avg*r).detach()
        # Finally, define L1 loss for the GradNorm
        L_grad = F.l1_loss(grad_norms_for_losses,  grad_target, reduction='sum')
        # Do optimization step for the loss coefficients
        self.weights_optimizer_.zero_grad()
        L_grad.backward(retain_graph=True)
        self.weights_optimizer_.step()

        # Renormalize weights (keep sum = num_tasks)
        with torch.no_grad():
            self.loss_weights_.data = self.loss_weights_.data * self.num_losses / self.loss_weights_.data.sum()
            self.loss_weights_.data = torch.clamp(self.loss_weights_.data, min=0.1)  # Prevent weights from going to 0
            # weights = self.loss_weights_.data.detach()
            weights = self.loss_weights_.detach().clone()
            self.state = {
                'WA': weights[0].item(),
                'FA': weights[1].item()
            }
        return self.state

    def get_current_weights(self):
        return self.state

    def get_current_gradient_similarities(self):
        return self.gradient_similarities