"""Arguments commonly used across the data processing pipeline"""
import argparse

def set_pipeline_args():
    """
       Sets up command line arguments parsing for all our main pipelines
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--cossad_data_path", type=str,
                        help='Path to the Cossad dataset')
    parser.add_argument("--object_classes", type=str, default=None,
                        help='Names of the object classes to run the program upon')
    parser.add_argument("--do_visualize", action='store_true',
                        help='Visualize point clouds along with the registration template')
    parser.add_argument("--do_random_rotate", action='store_true',
                        help='Randomly rotate the test object (using during ')
    parser.add_argument("--obj_per_class", type=int, default=1000,
                        help='Process only a given number of objects per class. Used for debugging / visulization')
    parser.add_argument('--encoder', type=str, default='fpfh',
                        help='Type of an encoder to use to extract features. Possible values'
                             'riconv2: RIConv++ network; fpfh: FPFH descriptor; '
                             'pointnet, pointnet2_ssg, pointnet2_msg: PointNet++ (deprecated)')
    parser.add_argument('--contrastive_encoder_path', type=str, default=None,
                        help='Path to the weights of the pretrained contrastive encoder')
    parser.add_argument('--max_registration_attempts', type=int, default=5,
                        help='The number of tries to do the best registration for registration-based pipeline')
    parser.add_argument("--patch_radius", type=float, default=2.0,
                        help='The radius of a patch to be selected. If we are using a contrastive feature extractor, '
                        'it must be exactly the radius of the patch in the training set')
    parser.add_argument("--points_per_patch", type=int, default=512,
                        help='The original patch, extracted from the point cloud, will be re-sampled to this given '
                             'number of points before being sent to a contrastive feature extractor')
    parser.add_argument("--embedding_dim", type=int, default=64,
                        help='The dimensionality of the embedding (i.e. a representation) generated by a feature '
                             'extractor')
    # args = parser.parse_args()
    return parser
